### ISSUE TITLE
Ship eval results for upcoming meeting on 2/12

### ISSUE THREAD

**Issue by JasonLo** [bxia68/factsheet-generator#9]
Provide end-to-end example with Devesh eval's input, and return the results to Devesh.

**Comment by JasonLo** [comment]
Hi Bill, have you begun processing Devesh's data? If you need assistance or a discussion, please discuss it [here](https://github.com/UW-Macrostrat/factsheet-generator/issues/9). Our goal is to present initial results using Devesh's data by Monday, allowing time for further iterations next week.

**Comment by JasonLo** [comment]
Link to Devesh data: https://github.com/UW-xDD/USGS2023/tree/main/evals/graph_dataset

**Comment by bxia68** [comment]
I haven't started yet, but I'm planning on working on it tonight. I'll let you know if I have any questions.
